### ISSUE TITLE
robincar_glm2

### ISSUE THREAD

**Issue by tye27** [mbannick/RobinCar#19]
If I used 
RobinCar::robincar_glm2(df=dfSim,
                        treat_col = "A", response_col = "y", 
                        g_family = "nb", 
                        formula = as.formula("y ~ A + Xc + Xb"))

The outputs have errors and say:
Error in family$family : $ operator is invalid for atomic vectors
In addition: Warning message:
In func() : Prediction unbiasedness does not hold.

But if I used RobinCar::robincar_glm2(df=dfSim,
                        treat_col = "A", response_col = "y", 
                        g_family = "nb", 
                        formula = as.formula("y ~ A + Xc + Xb"))$result 

It will give correct outputs.

**Comment by mbannick** [comment]
Hi Ting, please see PR #20 -- I've fixed this issue. Thanks for finding!
